# Generated by Django 3.1.7 on 2021-02-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_auto_20210226_0816'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='realtor',
    #         name='is_mvp',
    #         field=models.BooleanField(default=False),
    #     ),
    # ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='is_mvp',
        ),
        migrations.AddField(
            model_name='realtor',
            name='is_mvp',
            field=models.BooleanField(default=False),
        ),
    ]
