# Generated by Django 3.1.7 on 2021-02-26 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0004_auto_20210226_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='hire_date',
            new_name='hire_data',
        ),
    ]
